<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Company extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('companies')->insert([
        [
          'name'    => 'Watson',
          'subname' => 'Mega',
          'street'  => 1,
          'purok' => 'mo',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Super mart.png',
          'approve'  => 1,
        ],  
        [
          'name'    => 'SuperMart',
          'subname' => 'cab',
          'street'  => 2,
          'purok' => 'mo',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Super mart.png',
          'approve'  => 1,
        ],  
        [
          'name'    => '7/11',
          'subname' => 'Mabini',
          'street'  => 3,
          'purok' => 'ko',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => '7 11.png',
          'approve'  => 1,
        ],  
        [
          'name'    => 'Mc Do',
          'subname' => 'sansianco',
          'street'  => 4,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'MC do.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'Biggs',
          'subname' => 'Mega',
          'street'  => 5,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Biggs.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'Jollibee',
          'subname' => 'Circum',
          'street'  => 6,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Jollibee.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'Mang Inasal',
          'subname' => 'Crossing',
          'street'  => 7,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Mang Inasal.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'KFC',
          'subname' => null,
          'street'  => 8,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'KFC.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'Pizza hut',
          'subname' => 'Sumacab',
          'street'  => 9,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Pizza Hut.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'Waves',
          'subname' => 'Mega Center',
          'street'  => 10,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Waves Bar.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'Greenwich',
          'subname' => 'Mega',
          'street'  => 11,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Greenwich.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'Pepsi',
          'subname' => 'Mega',
          'street'  => 12,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Pepsi.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'Chow King',
          'subname' => 'Mega',
          'street'  => 13,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Chow King.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'Pandayan book store',
          'subname' => 'Mega',
          'street'  => 14,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'pandayan.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'Savory',
          'subname' => 'Mega',
          'street'  => 15,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Savory.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'Visenticos',
          'subname' => 'Mega',
          'street'  => 16,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'vicenticos.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'National Bookstore',
          'subname' => 'Mega',
          'street'  => 17,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'national bookstore.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'Starbucks coffee',
          'subname' => 'Mega',
          'street'  => 18,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Starbuck.png',
          'approve'  => 1,
        ],
        [
          'name'    => 'Crocs',
          'subname' => 'Mega',
          'street'  => 19,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Crocs.png',
          'approve'  => null,
        ],
        [
          'name'    => 'Nail Glow',
          'subname' => 'Mega',
          'street'  => 20,
          'purok' => 'no',
          'brgy'  => 2356,
          'phone' => '0935-032-2659',
          'logo'  => 'Nail.png',
          'approve'  => null,
        ]
      ]);
    }
}
