<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;


class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('users')->insert([
        [
        'profile_picture' => 'superadmin.jpg',
        'name' =>'Christopher',
        'role_id' => 1,
        'email'    => 'christopher@wup.ctms.com',
        'password' => Hash::make('password'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'fname'   => 'Christopher',
        'mname'   => 'Batawig',
        'lname'   => 'Tolentino',
        'suffix'  => null,
        'is_male' => 1,
        'dob'     => '1997-04-29',
        'addR'     =>'Region III',
        'addP'     =>'Nueva Ecija',
        'addC'     =>'Cabanatuan',
        'addB'     =>'IV',
        'addPr'     => 'Mabini',
        'addH'     => 29,
        "phone"    =>'(951) 104-9783',
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
         [
        'profile_picture' => 'icon.jpg',
        'name' =>'Pathy',
        'role_id' => 2,
        'email'    => 'pathy@wup.ctms.com',
        'password' => Hash::make('password'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'fname'   => 'Pathy Leorey',
        'mname'   => 'Francisco',
        'lname'   => 'Samiling',
        'suffix'  => null,
        'is_male' => 1,
        'dob'     => '1999-02-23',
        'addR'     =>'Region III',
        'addP'     =>'Nueva Ecija',
        'addC'     =>'Cabanatuan',
        'addB'     =>'Valle Cruz',
        'addPr'     =>'Paros',
        'addH'     =>'Block 12, Lot 23',
        "phone"    =>'(966) 697-4691',
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
        [
        'profile_picture' => 'icon.jpg',
        'name' =>'Lexbron',
        'role_id' => 3,
        'email'    => 'lexbron@wup.ctms.com',
        'password' => Hash::make('password'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'fname'   => 'Lexter Maynard',
        'mname'   => 'Alamon',
        'lname'   => 'Dela Cruz',
        'suffix'  => null,
        'is_male' => 1,
        'dob'     => '1997-10-04',
        'addR'     =>'Region III',
        'addP'     =>'Nueva Ecija',
        'addC'     =>'Llanera',
        'addB'     =>'Casile',
        'addPr'     =>'Sumilang',
        'addH'     => 68,
        "phone"    =>'(930) 385-2397',
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
        [
        'profile_picture' => 'icon.jpg',
        'name' =>'Sam',
        'role_id' => 3,
        'email'    => 'sam@wup.ctms.com',
        'password' => Hash::make('password'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'fname'   => 'Sam Justine',
        'mname'   => 'Fajardo',
        'lname'   => 'Bote',
        'suffix'  => null,
        'is_male' => 1,
        'dob'     => '1996-06-24',
        'addR'     =>'Region III',
        'addP'     =>'Nueva Ecija',
        'addC'     =>'General Tinio',
        'addB'     =>'San Pedro',
        'addPr'     =>'Gulod',
        'addH'     => 'spo-560',
        "phone"    =>'(927) 013-2914',
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
        [
        'profile_picture' => 'icon.jpg',
        'name' =>'Ynock',
        'role_id' => 3,
        'email'    => 'ynock@wup.ctms.com',
        'password' => Hash::make('password'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'fname'   => 'Cris Alex',
        'mname'   => 'Pausing',
        'lname'   => 'Abalos',
        'suffix'  => null,
        'is_male' => 1,
        'dob'     => '1994-04-16',
        'addR'     =>'Region III',
        'addP'     =>'Nueva Ecija',
        'addC'     =>'Pantabangan',
        'addB'     =>'West Poblacion',
        'addPr'     => 3,
        'addH'     => 041,
        "phone"    =>'(961) 191-5771',
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
        [
        'profile_picture' => 'icon.jpg',
        'name' =>'Earvin',
        'role_id' => 3,
        'email'    => 'earvin@wup.ctms.com',
        'password' => Hash::make('password'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'fname'   => 'Earvin Michael',
        'mname'   => 'Francisco',
        'lname'   => 'De Leon',
        'suffix'  => null,
        'is_male' => 1,
        'dob'     => '1998-06-05',
        'addR'     =>'Region III',
        'addP'     =>'Nueva Ecija',
        'addC'     =>'San Leonardo',
        'addB'     =>'San Anton',
        'addPr'     => 3,
        'addH'     => null,
        "phone"    =>'(936) 663-8452',
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
        [
        'profile_picture' => 'icon.jpg',
        'name' =>'Brant',
        'role_id' => 3,
        'email'    => 'brant@wup.ctms.com',
        'password' => Hash::make('password'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'fname'   => 'Brant Dave',
        'mname'   => 'Cabalteja',
        'lname'   => 'Granado',
        'suffix'  => null,
        'is_male' => 1,
        'dob'     => '1998-08-20',
        'addR'     =>'Region III',
        'addP'     =>'Nueva Ecija',
        'addC'     =>'Cabanatuan',
        'addB'     =>'Bangad',
        'addPr'     => 3,
        'addH'     => null,
        "phone"    =>'(916) 244-3346',
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ],
      ]);
    }
}
